KERNEL= 5
THRESH = 1
STATS='median'
PLOT_PATH='../data/processed/plots/'
NC_PATH='../data/processed/netcdf/'
flow_var='cloud_top_pressure'
DATE_FORMAT="%m-%d-%Y-%H:%M:%S"
FOLDER='01_28_21'
temp_thresh=253
dt=3600